lang: python

python: 2.7

install:
  - wget http://ats.borqs.com/smartserver/static/runner.tar.gz
  - tar zxvf runner.tar.gz
  - rm runner.tar.gz
  - mv runner runner_tmp
  - mv runner_tmp/* .
  - rm -rf runner_tmp
  - sed 's/tablet_jellybean/repo/g' setup.py
  - ./install.py

script:
  - python run.py --loop 1
