lang: python

python: 2.7

install:
  - wget http://ats.borqs.com/smartserver/static/runner.tar.gz
  - tar zxvf runner.tar.gz
  - rm runner.tar.gz
  - mv runner/* .
  - rm -rf runner

script:
  - python run.py --loop 1
